import request from '@/utils/request'

export function businessChannelList(query) {
/*  return request({
    url: '/statistics/business-channel-list',
    method: 'get',
    params: query
  })*/

  return new Promise((resolve, reject) => {
    const res = {
      'code': 20000,
      'data': {
        'items': [
          {
            'category': 'businessChanne',
            'id': 537168,
            'title': '什身交制',
            'channelTag': 'hnypdsqos',
            'tableCount': 9,
            'creator': '孟涛',
            'channelOrigin': 'sntpktd',
            'pushMatched': 7000,
            'pushStatus': 4402,
            'pushSucceed': 7627,
            'pushFailed': 4779,
            'feedback': 7435,
            'lastPushTime': '2005-04-09 12:50:48'
          },
          {
            'category': 'businessChanne',
            'id': 396960,
            'title': '计两队级',
            'channelTag': 'xsk',
            'tableCount': 62,
            'creator': '金军',
            'channelOrigin': 'nherdn',
            'pushMatched': 7111,
            'pushStatus': 1552,
            'pushSucceed': 9769,
            'pushFailed': 8697,
            'feedback': 5388,
            'lastPushTime': '2013-04-21 17:01:42'
          },
          {
            'category': 'businessChanne',
            'id': 789942,
            'title': '类正离命知',
            'channelTag': 'xfyluilid',
            'tableCount': 30,
            'creator': '何刚',
            'channelOrigin': 'mhzlxclh',
            'pushMatched': 7422,
            'pushStatus': 3846,
            'pushSucceed': 5037,
            'pushFailed': 9552,
            'feedback': 8589,
            'lastPushTime': '1971-08-18 12:23:15'
          },
          {
            'category': 'businessChanne',
            'id': 328966,
            'title': '是家红人',
            'channelTag': 'lkrhvobew',
            'tableCount': 79,
            'creator': '郭艳',
            'channelOrigin': 'fpwr',
            'pushMatched': 6838,
            'pushStatus': 5348,
            'pushSucceed': 9523,
            'pushFailed': 1578,
            'feedback': 8481,
            'lastPushTime': '2018-01-12 22:34:46'
          },
          {
            'category': 'businessChanne',
            'id': 250460,
            'title': '江极信转观身',
            'channelTag': 'znci',
            'tableCount': 92,
            'creator': '史丽',
            'channelOrigin': 'rczlcohsqs',
            'pushMatched': 6491,
            'pushStatus': 7749,
            'pushSucceed': 7183,
            'pushFailed': 9880,
            'feedback': 8462,
            'lastPushTime': '1987-01-09 23:00:58'
          },
          {
            'category': 'businessChanne',
            'id': 794099,
            'title': '增气记片收地专',
            'channelTag': 'apitkynn',
            'tableCount': 26,
            'creator': '毛杰',
            'channelOrigin': 'xujwzzvf',
            'pushMatched': 9295,
            'pushStatus': 867,
            'pushSucceed': 697,
            'pushFailed': 1659,
            'feedback': 564,
            'lastPushTime': '1995-12-18 15:51:41'
          },
          {
            'category': 'businessChanne',
            'id': 110156,
            'title': '题高改多候',
            'channelTag': 'xnfdgw',
            'tableCount': 26,
            'creator': '廖超',
            'channelOrigin': 'srcbrwp',
            'pushMatched': 560,
            'pushStatus': 8826,
            'pushSucceed': 1983,
            'pushFailed': 4682,
            'feedback': 5716,
            'lastPushTime': '2001-03-22 15:52:40'
          },
          {
            'category': 'businessChanne',
            'id': 688986,
            'title': '教说府一小',
            'channelTag': 'yplzscwb',
            'tableCount': 37,
            'creator': '龙秀兰',
            'channelOrigin': 'nwvvgctl',
            'pushMatched': 1936,
            'pushStatus': 4406,
            'pushSucceed': 4939,
            'pushFailed': 4730,
            'feedback': 6917,
            'lastPushTime': '1992-03-20 12:06:51'
          },
          {
            'category': 'businessChanne',
            'id': 695801,
            'title': '那些装听低声色',
            'channelTag': 'kwxcvus',
            'tableCount': 38,
            'creator': '卢超',
            'channelOrigin': 'txmdgos',
            'pushMatched': 3076,
            'pushStatus': 8311,
            'pushSucceed': 8370,
            'pushFailed': 5791,
            'feedback': 8104,
            'lastPushTime': '2020-01-13 12:08:04'
          },
          {
            'category': 'businessChanne',
            'id': 793578,
            'title': '进教代心花放',
            'channelTag': 'lalkkqn',
            'tableCount': 29,
            'creator': '石磊',
            'channelOrigin': 'qoxogro',
            'pushMatched': 3435,
            'pushStatus': 8477,
            'pushSucceed': 8971,
            'pushFailed': 8947,
            'feedback': 5470,
            'lastPushTime': '2009-07-20 11:54:06'
          },
          {
            'category': 'businessChanne',
            'id': 412762,
            'title': '格县部易',
            'channelTag': 'cyx',
            'tableCount': 9,
            'creator': '金军',
            'channelOrigin': 'sidblci',
            'pushMatched': 2365,
            'pushStatus': 6206,
            'pushSucceed': 5624,
            'pushFailed': 9442,
            'feedback': 1452,
            'lastPushTime': '2014-02-08 13:43:30'
          },
          {
            'category': 'businessChanne',
            'id': 584838,
            'title': '严林目理理',
            'channelTag': 'ushdzsicy',
            'tableCount': 19,
            'creator': '秦敏',
            'channelOrigin': 'udpyj',
            'pushMatched': 8077,
            'pushStatus': 4037,
            'pushSucceed': 890,
            'pushFailed': 5318,
            'feedback': 8701,
            'lastPushTime': '2018-10-26 00:12:37'
          },
          {
            'category': 'businessChanne',
            'id': 850323,
            'title': '界平有从',
            'channelTag': 'kfdipv',
            'tableCount': 4,
            'creator': '叶秀英',
            'channelOrigin': 'vtssquvpgw',
            'pushMatched': 3883,
            'pushStatus': 4072,
            'pushSucceed': 7004,
            'pushFailed': 6504,
            'feedback': 7388,
            'lastPushTime': '2014-07-28 11:34:55'
          },
          {
            'category': 'businessChanne',
            'id': 590894,
            'title': '进我引更',
            'channelTag': 'vuxexfmqo',
            'tableCount': 45,
            'creator': '邵伟',
            'channelOrigin': 'vpuufof',
            'pushMatched': 240,
            'pushStatus': 7314,
            'pushSucceed': 5265,
            'pushFailed': 9416,
            'feedback': 408,
            'lastPushTime': '1996-08-04 00:49:00'
          },
          {
            'category': 'businessChanne',
            'id': 902681,
            'title': '角断型院劳很党',
            'channelTag': 'srfykdp',
            'tableCount': 47,
            'creator': '邱静',
            'channelOrigin': 'aanlev',
            'pushMatched': 1149,
            'pushStatus': 5528,
            'pushSucceed': 5374,
            'pushFailed': 5958,
            'feedback': 8555,
            'lastPushTime': '1970-10-05 11:42:40'
          },
          {
            'category': 'businessChanne',
            'id': 754800,
            'title': '受发象',
            'channelTag': 'nvuzvr',
            'tableCount': 82,
            'creator': '赵秀兰',
            'channelOrigin': 'qtuxlmd',
            'pushMatched': 5462,
            'pushStatus': 5932,
            'pushSucceed': 463,
            'pushFailed': 4309,
            'feedback': 8786,
            'lastPushTime': '2019-06-11 18:10:29'
          },
          {
            'category': 'businessChanne',
            'id': 239567,
            'title': '地积使住',
            'channelTag': 'ngg',
            'tableCount': 32,
            'creator': '曹娟',
            'channelOrigin': 'jydujxjz',
            'pushMatched': 4877,
            'pushStatus': 4459,
            'pushSucceed': 2781,
            'pushFailed': 2169,
            'feedback': 7213,
            'lastPushTime': '1981-12-05 16:45:38'
          },
          {
            'category': 'businessChanne',
            'id': 685583,
            'title': '这确各选',
            'channelTag': 'qpdhebvghr',
            'tableCount': 26,
            'creator': '高芳',
            'channelOrigin': 'lwyik',
            'pushMatched': 567,
            'pushStatus': 8577,
            'pushSucceed': 3228,
            'pushFailed': 6791,
            'feedback': 1708,
            'lastPushTime': '1987-06-20 20:29:46'
          },
          {
            'category': 'businessChanne',
            'id': 764587,
            'title': '至精且',
            'channelTag': 'ggaaqwsjgv',
            'tableCount': 5,
            'creator': '孔平',
            'channelOrigin': 'tmnqjyicei',
            'pushMatched': 7097,
            'pushStatus': 2755,
            'pushSucceed': 7291,
            'pushFailed': 4141,
            'feedback': 3840,
            'lastPushTime': '1997-12-14 08:23:47'
          },
          {
            'category': 'businessChanne',
            'id': 375846,
            'title': '片比着级子计',
            'channelTag': 'eottutb',
            'tableCount': 83,
            'creator': '石娟',
            'channelOrigin': 'gautqtc',
            'pushMatched': 1958,
            'pushStatus': 9825,
            'pushSucceed': 3414,
            'pushFailed': 7427,
            'feedback': 1982,
            'lastPushTime': '1983-01-18 17:25:11'
          }
        ],
        'total': 1627
      }
    }
    resolve(res)
  })
}
export function contentList(query) {
/*  return request({
    url: '/statistics/content-list',
    method: 'get',
    params: query
  })*/
  return new Promise((resolve, reject) => {
    const res = {
      'code': 20000,
      'data': {
        'items': [
          {
            'category': 'businessChanne',
            'id': 948868,
            'title': '声然铁海各深',
            'contentType': 'utgfds',
            'creator': '范超',
            'contentOrigin': 'fuidpt',
            'pushMatched': 3334,
            'pushStatus': 4134,
            'pushSucceed': 5841,
            'pushFailed': 3867,
            'feedback': 169,
            'lastPushTime': '1994-06-04 04:59:50',
            'contentTag': 'pvsne'
          },
          {
            'category': 'businessChanne',
            'id': 872057,
            'title': '子党作值至',
            'contentType': 'syep',
            'creator': '何敏',
            'contentOrigin': 'lggb',
            'pushMatched': 9554,
            'pushStatus': 1834,
            'pushSucceed': 8545,
            'pushFailed': 9837,
            'feedback': 9837,
            'lastPushTime': '1972-02-20 14:48:05',
            'contentTag': 'ydvptpdivt'
          },
          {
            'category': 'businessChanne',
            'id': 859184,
            'title': '问等铁华住不',
            'contentType': 'djhseq',
            'creator': '叶秀兰',
            'contentOrigin': 'jxwbvp',
            'pushMatched': 2657,
            'pushStatus': 3593,
            'pushSucceed': 104,
            'pushFailed': 8868,
            'feedback': 2815,
            'lastPushTime': '2012-12-18 01:18:39',
            'contentTag': 'upeuspjlj'
          },
          {
            'category': 'businessChanne',
            'id': 107500,
            'title': '标达需阶受',
            'contentType': 'rwjddg',
            'creator': '梁敏',
            'contentOrigin': 'wlvbyqg',
            'pushMatched': 4231,
            'pushStatus': 9098,
            'pushSucceed': 7836,
            'pushFailed': 7722,
            'feedback': 9716,
            'lastPushTime': '1981-08-10 09:19:13',
            'contentTag': 'xcgblw'
          },
          {
            'category': 'businessChanne',
            'id': 687144,
            'title': '展许命意件',
            'contentType': 'wuodkfgl',
            'creator': '余明',
            'contentOrigin': 'osd',
            'pushMatched': 650,
            'pushStatus': 2096,
            'pushSucceed': 942,
            'pushFailed': 9767,
            'feedback': 7551,
            'lastPushTime': '2016-12-16 05:24:51',
            'contentTag': 'iudrxoe'
          },
          {
            'category': 'businessChanne',
            'id': 190986,
            'title': '学想立关实段',
            'contentType': 'vozbzj',
            'creator': '毛杰',
            'contentOrigin': 'bmwv',
            'pushMatched': 6410,
            'pushStatus': 3951,
            'pushSucceed': 818,
            'pushFailed': 1650,
            'feedback': 8699,
            'lastPushTime': '1982-03-01 16:45:18',
            'contentTag': 'rdrk'
          },
          {
            'category': 'businessChanne',
            'id': 790091,
            'title': '量必布酸',
            'contentType': 'hfjokxp',
            'creator': '谭勇',
            'contentOrigin': 'bsenmfcgkt',
            'pushMatched': 7433,
            'pushStatus': 8989,
            'pushSucceed': 5739,
            'pushFailed': 7643,
            'feedback': 705,
            'lastPushTime': '1974-12-30 15:30:40',
            'contentTag': 'kiwrw'
          },
          {
            'category': 'businessChanne',
            'id': 114118,
            'title': '制七观手',
            'contentType': 'jwiem',
            'creator': '董敏',
            'contentOrigin': 'hyeljdwnd',
            'pushMatched': 9394,
            'pushStatus': 3481,
            'pushSucceed': 8620,
            'pushFailed': 6757,
            'feedback': 9192,
            'lastPushTime': '1975-07-25 15:52:54',
            'contentTag': 'xxsdioz'
          },
          {
            'category': 'businessChanne',
            'id': 383780,
            'title': '或力江你',
            'contentType': 'foerg',
            'creator': '周静',
            'contentOrigin': 'ewnwstms',
            'pushMatched': 2597,
            'pushStatus': 1211,
            'pushSucceed': 2636,
            'pushFailed': 1895,
            'feedback': 795,
            'lastPushTime': '1996-08-12 03:08:31',
            'contentTag': 'ndqkdkh'
          },
          {
            'category': 'businessChanne',
            'id': 200082,
            'title': '格由每般如劳',
            'contentType': 'cicwdk',
            'creator': '许娜',
            'contentOrigin': 'gshr',
            'pushMatched': 3748,
            'pushStatus': 7857,
            'pushSucceed': 1290,
            'pushFailed': 3823,
            'feedback': 3788,
            'lastPushTime': '1992-09-07 16:53:36',
            'contentTag': 'cvs'
          },
          {
            'category': 'businessChanne',
            'id': 371079,
            'title': '斗拉务儿',
            'contentType': 'qkdrquqf',
            'creator': '任杰',
            'contentOrigin': 'kpfrc',
            'pushMatched': 2869,
            'pushStatus': 7308,
            'pushSucceed': 1341,
            'pushFailed': 9627,
            'feedback': 5408,
            'lastPushTime': '1988-02-12 16:19:00',
            'contentTag': 'nbvgc'
          },
          {
            'category': 'businessChanne',
            'id': 463440,
            'title': '道体位个科此',
            'contentType': 'fydxfx',
            'creator': '叶芳',
            'contentOrigin': 'iuob',
            'pushMatched': 601,
            'pushStatus': 4841,
            'pushSucceed': 4345,
            'pushFailed': 328,
            'feedback': 7540,
            'lastPushTime': '1980-04-08 00:41:15',
            'contentTag': 'dtqpjl'
          },
          {
            'category': 'businessChanne',
            'id': 365375,
            'title': '容政传影',
            'contentType': 'xiuunljv',
            'creator': '杨勇',
            'contentOrigin': 'vbpkp',
            'pushMatched': 3011,
            'pushStatus': 4323,
            'pushSucceed': 6182,
            'pushFailed': 935,
            'feedback': 7750,
            'lastPushTime': '1970-04-19 18:45:01',
            'contentTag': 'lomsu'
          },
          {
            'category': 'businessChanne',
            'id': 406003,
            'title': '社积自书济西今',
            'contentType': 'fujwcn',
            'creator': '沈涛',
            'contentOrigin': 'ilnrlem',
            'pushMatched': 8650,
            'pushStatus': 6462,
            'pushSucceed': 9789,
            'pushFailed': 8243,
            'feedback': 9348,
            'lastPushTime': '1978-06-02 07:56:02',
            'contentTag': 'ayheqwd'
          },
          {
            'category': 'businessChanne',
            'id': 447524,
            'title': '且千办长物维',
            'contentType': 'jtxwpghz',
            'creator': '金秀英',
            'contentOrigin': 'fvdmarbmxp',
            'pushMatched': 2632,
            'pushStatus': 6722,
            'pushSucceed': 4936,
            'pushFailed': 1896,
            'feedback': 5115,
            'lastPushTime': '2008-01-26 19:25:23',
            'contentTag': 'vkknxnsb'
          },
          {
            'category': 'businessChanne',
            'id': 223493,
            'title': '用个例劳记每',
            'contentType': 'wdjvkud',
            'creator': '彭艳',
            'contentOrigin': 'szapqkfs',
            'pushMatched': 3387,
            'pushStatus': 7509,
            'pushSucceed': 7171,
            'pushFailed': 6823,
            'feedback': 4359,
            'lastPushTime': '2007-11-18 11:17:05',
            'contentTag': 'hmjukm'
          },
          {
            'category': 'businessChanne',
            'id': 870675,
            'title': '划点决由外',
            'contentType': 'uiblofxc',
            'creator': '汪杰',
            'contentOrigin': 'sflser',
            'pushMatched': 9471,
            'pushStatus': 7229,
            'pushSucceed': 9127,
            'pushFailed': 2513,
            'feedback': 8052,
            'lastPushTime': '1988-09-05 04:22:07',
            'contentTag': 'ugrscjcpx'
          },
          {
            'category': 'businessChanne',
            'id': 484118,
            'title': '对前头报科',
            'contentType': 'xmx',
            'creator': '白丽',
            'contentOrigin': 'onfiff',
            'pushMatched': 9869,
            'pushStatus': 3617,
            'pushSucceed': 7356,
            'pushFailed': 5636,
            'feedback': 4656,
            'lastPushTime': '1985-04-17 14:04:43',
            'contentTag': 'pnbccfjs'
          },
          {
            'category': 'businessChanne',
            'id': 141870,
            'title': '置数反条九联',
            'contentType': 'iryru',
            'creator': '曾艳',
            'contentOrigin': 'cvokr',
            'pushMatched': 5791,
            'pushStatus': 2821,
            'pushSucceed': 5385,
            'pushFailed': 5261,
            'feedback': 2313,
            'lastPushTime': '2011-06-10 16:19:55',
            'contentTag': 'het'
          },
          {
            'category': 'businessChanne',
            'id': 650137,
            'title': '集步量',
            'contentType': 'dlno',
            'creator': '刘娜',
            'contentOrigin': 'bhfum',
            'pushMatched': 1013,
            'pushStatus': 9152,
            'pushSucceed': 6261,
            'pushFailed': 1465,
            'feedback': 979,
            'lastPushTime': '1990-08-26 12:56:34',
            'contentTag': 'pqyijosqr'
          }
        ],
        'total': 87780
      }
    }
    resolve(res)
  })
}
export function pipeList(query) {
/*  return request({
    url: '/statistics/pipe-list',
    method: 'get',
    params: query
  })*/
  return new Promise((resolve, reject) => {
    const res = {
      'code': 20000,
      'data': {
        'items': [
          {
            'id': 830124,
            'title': '非层列化住意',
            'pipeTag': 'odrjkum',
            'pushMatched': 4362,
            'pushStatus': 3465,
            'pushSucceed': 1650,
            'pushFailed': 2565,
            'feedback': 3810,
            'lastPushTime': '1980-08-20 08:22:48',
            'category': 'businessChanne',
            'pipeType': 'xeoek'
          },
          {
            'id': 637925,
            'title': '变白所么六',
            'pipeTag': 'eucxghsf',
            'pushMatched': 5621,
            'pushStatus': 8559,
            'pushSucceed': 3985,
            'pushFailed': 9877,
            'feedback': 253,
            'lastPushTime': '2012-01-22 16:44:55',
            'category': 'businessChanne',
            'pipeType': 'lztwp'
          },
          {
            'id': 488147,
            'title': '制到例于力',
            'pipeTag': 'lkfedg',
            'pushMatched': 8159,
            'pushStatus': 2561,
            'pushSucceed': 4603,
            'pushFailed': 1055,
            'feedback': 5814,
            'lastPushTime': '2004-09-18 04:03:35',
            'category': 'businessChanne',
            'pipeType': 'hmw'
          },
          {
            'id': 950090,
            'title': '个其知维由斯',
            'pipeTag': 'osnqk',
            'pushMatched': 7291,
            'pushStatus': 5245,
            'pushSucceed': 263,
            'pushFailed': 9184,
            'feedback': 5845,
            'lastPushTime': '1978-11-22 22:52:24',
            'category': 'businessChanne',
            'pipeType': 'vocukmch'
          },
          {
            'id': 359536,
            'title': '确候先开声',
            'pipeTag': 'jraholm',
            'pushMatched': 3300,
            'pushStatus': 5637,
            'pushSucceed': 7117,
            'pushFailed': 9134,
            'feedback': 2305,
            'lastPushTime': '1984-03-02 20:32:32',
            'category': 'businessChanne',
            'pipeType': 'jupsjes'
          },
          {
            'id': 264093,
            'title': '采处二自六见',
            'pipeTag': 'jwyfd',
            'pushMatched': 7787,
            'pushStatus': 4863,
            'pushSucceed': 1341,
            'pushFailed': 5801,
            'feedback': 1829,
            'lastPushTime': '2001-03-02 12:37:36',
            'category': 'businessChanne',
            'pipeType': 'mxlx'
          },
          {
            'id': 759623,
            'title': '天切位温了',
            'pipeTag': 'cpwg',
            'pushMatched': 5475,
            'pushStatus': 3362,
            'pushSucceed': 5382,
            'pushFailed': 5844,
            'feedback': 5151,
            'lastPushTime': '2004-08-21 13:52:26',
            'category': 'businessChanne',
            'pipeType': 'qsqhzmslm'
          },
          {
            'id': 668623,
            'title': '制平广工反',
            'pipeTag': 'jgruh',
            'pushMatched': 3998,
            'pushStatus': 4783,
            'pushSucceed': 9603,
            'pushFailed': 3754,
            'feedback': 4932,
            'lastPushTime': '2004-08-30 22:28:01',
            'category': 'businessChanne',
            'pipeType': 'cvaz'
          },
          {
            'id': 855267,
            'title': '变京好育现压',
            'pipeTag': 'xox',
            'pushMatched': 8116,
            'pushStatus': 5416,
            'pushSucceed': 9075,
            'pushFailed': 853,
            'feedback': 4326,
            'lastPushTime': '2000-01-16 16:33:30',
            'category': 'businessChanne',
            'pipeType': 'xiocwltfu'
          },
          {
            'id': 447453,
            'title': '当存全格志命',
            'pipeTag': 'rrsfymoz',
            'pushMatched': 4860,
            'pushStatus': 2681,
            'pushSucceed': 9564,
            'pushFailed': 2244,
            'feedback': 9088,
            'lastPushTime': '1972-08-24 21:49:24',
            'category': 'businessChanne',
            'pipeType': 'tkygifjcky'
          },
          {
            'id': 789418,
            'title': '包间被量斯',
            'pipeTag': 'awtm',
            'pushMatched': 9864,
            'pushStatus': 5037,
            'pushSucceed': 6284,
            'pushFailed': 7034,
            'feedback': 9276,
            'lastPushTime': '1976-10-24 01:12:57',
            'category': 'businessChanne',
            'pipeType': 'xmrzvd'
          },
          {
            'id': 542760,
            'title': '经快约合强调',
            'pipeTag': 'fuzina',
            'pushMatched': 1177,
            'pushStatus': 3325,
            'pushSucceed': 9701,
            'pushFailed': 9486,
            'feedback': 9530,
            'lastPushTime': '2014-06-17 22:38:45',
            'category': 'businessChanne',
            'pipeType': 'zkc'
          },
          {
            'id': 888617,
            'title': '向技老',
            'pipeTag': 'epb',
            'pushMatched': 961,
            'pushStatus': 3556,
            'pushSucceed': 8663,
            'pushFailed': 4193,
            'feedback': 8771,
            'lastPushTime': '1982-02-27 10:08:36',
            'category': 'businessChanne',
            'pipeType': 'dyvkoq'
          },
          {
            'id': 207685,
            'title': '感般出道群',
            'pipeTag': 'koa',
            'pushMatched': 1792,
            'pushStatus': 9128,
            'pushSucceed': 7681,
            'pushFailed': 7759,
            'feedback': 2680,
            'lastPushTime': '2007-03-19 07:46:07',
            'category': 'businessChanne',
            'pipeType': 'fjvrtcm'
          },
          {
            'id': 150226,
            'title': '并九示老见办',
            'pipeTag': 'jthzen',
            'pushMatched': 6008,
            'pushStatus': 2891,
            'pushSucceed': 5479,
            'pushFailed': 6061,
            'feedback': 770,
            'lastPushTime': '1988-02-17 11:56:24',
            'category': 'businessChanne',
            'pipeType': 'xigecjk'
          },
          {
            'id': 857862,
            'title': '设收外情外',
            'pipeTag': 'tfupur',
            'pushMatched': 8407,
            'pushStatus': 8560,
            'pushSucceed': 9615,
            'pushFailed': 7915,
            'feedback': 7093,
            'lastPushTime': '1973-11-15 00:46:58',
            'category': 'businessChanne',
            'pipeType': 'cmjoeqape'
          },
          {
            'id': 870789,
            'title': '品革王化',
            'pipeTag': 'fxrbnlopb',
            'pushMatched': 3691,
            'pushStatus': 7036,
            'pushSucceed': 1959,
            'pushFailed': 2000,
            'feedback': 9081,
            'lastPushTime': '2005-11-12 18:53:33',
            'category': 'businessChanne',
            'pipeType': 'idj'
          },
          {
            'id': 994002,
            'title': '头派备住区段',
            'pipeTag': 'kqj',
            'pushMatched': 474,
            'pushStatus': 418,
            'pushSucceed': 173,
            'pushFailed': 2701,
            'feedback': 8917,
            'lastPushTime': '1989-12-31 03:22:36',
            'category': 'businessChanne',
            'pipeType': 'ktdyrcl'
          },
          {
            'id': 826768,
            'title': '组化金标',
            'pipeTag': 'ooxlm',
            'pushMatched': 1070,
            'pushStatus': 8054,
            'pushSucceed': 6326,
            'pushFailed': 8124,
            'feedback': 2078,
            'lastPushTime': '1970-05-21 20:15:38',
            'category': 'businessChanne',
            'pipeType': 'mrrs'
          },
          {
            'id': 956818,
            'title': '入可准没题',
            'pipeTag': 'izdwrltguw',
            'pushMatched': 8383,
            'pushStatus': 2881,
            'pushSucceed': 2109,
            'pushFailed': 5924,
            'feedback': 8385,
            'lastPushTime': '1981-03-31 11:26:49',
            'category': 'businessChanne',
            'pipeType': 'gowjfrval'
          }
        ],
        'total': 35555
      }
    }
    resolve(res)
  })
}

export function detail(query) {
  return request({
    url: '/statistics/detail',
    method: 'get',
    params: query
  })
}

export function download(query) {
  return request({
    url: '/statistics/export',
    method: 'get',
    params: query
  })
}
